name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        run: |
          # Install dependencies for ruby-build
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
          
          # Install ruby-build
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh
          cd ..
          
          # Create Ruby installation directory
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.3.0/x64
          
          # Install Ruby
          sudo ruby-build 3.3.0 /opt/hostedtoolcache/Ruby/3.3.0/x64
          
          # Set permissions for the Ruby directory
          sudo chown -R $USER:$USER /opt/hostedtoolcache/Ruby/3.3.0/x64
          
          # Mark installation as complete
          sudo touch /opt/hostedtoolcache/Ruby/3.3.0/x64.complete
          
          # Add Ruby to PATH
          echo "/opt/hostedtoolcache/Ruby/3.3.0/x64/bin" >> $GITHUB_PATH
          
          # Install bundler with correct permissions
          /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/gem install bundler

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          # Ensure bundle config directory exists and has correct permissions
          mkdir -p ~/.bundle
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
