name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          
          # Create and set proper permissions for gem directories
          mkdir -p $HOME/.gem/ruby/3.2.0
          chmod -R 755 $HOME/.gem
          
          # Set secure gem environment with correct Ruby version path
          export GEM_HOME="$HOME/.gem/ruby/3.2.0"
          export GEM_PATH="$HOME/.gem/ruby/3.2.0"
          export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
          
          # Install bundler with explicit user permissions
          gem install --user-install bundler
          
          # Verify installation and permissions
          which bundle
          ruby -v
          bundle -v

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        env:
          GEM_HOME: "$HOME/.gem/ruby/3.2.0"
          GEM_PATH: "$HOME/.gem/ruby/3.2.0"
          PATH: "$HOME/.gem/ruby/3.2.0/bin:$PATH"
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs=4 --retry=3

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
          GEM_HOME: "$HOME/.gem/ruby/3.2.0"
          GEM_PATH: "$HOME/.gem/ruby/3.2.0"
          PATH: "$HOME/.gem/ruby/3.2.0/bin:$PATH"
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4